name: Deno CI (test)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macOS-latest, windows-latest]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Cache Deno
        id: cache-deno
        uses: actions/cache@v3
        with:
            path: ~/.cache/deno
            # Might need a hash of the lock file here?
            key: ${{ matrix.os }}-deno-gateway-tools

      - name: Check format
        if: matrix.os == 'ubuntu-22.04'
        run: deno fmt --check

      - name: Check linting
        if: matrix.os == 'ubuntu-22.04'
        run: deno lint

      - name: Tests
        run: deno task test
